//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damage.DataAccess.Models
{
    using System.Data.Entity;

    public partial class Entities : DbContext
    {
    	public Entities(string connectionString): base(connectionString)
    	{
    		Database.SetInitializer<Entities>(null);
    	}
    
    	public DbSet<Gadget> Gadgets { get; set; }
    	public DbSet<UserGadget> UserGadgets { get; set; }
    	public DbSet<User> Users { get; set; }
    }
}
