//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damage.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gadget
    {
        public Gadget()
        {
            this.UserGadgets = new HashSet<UserGadget>();
        }
    
        public int GadgetId { get; set; }
        public string GadgetName { get; set; }
        public string GadgetTitle { get; set; }
        public string GadgetDescription { get; set; }
        public string GadgetVersion { get; set; }
        public bool RequiresValidGoogleAccessToken { get; set; }
        public bool InBeta { get; set; }
        public bool AssemblyPresent { get; set; }
        public string DefaultSettings { get; set; }
        public string SettingsSchema { get; set; }
    
        public virtual ICollection<UserGadget> UserGadgets { get; set; }
    }
}
