//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damage.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserGadgets = new HashSet<UserGadget>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string CurrentOAuthAccessToken { get; set; }
        public System.DateTime OAuthAccessTokenExpiration { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public int LayoutId { get; set; }
    
        public virtual ICollection<UserGadget> UserGadgets { get; set; }
    }
}
