//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damage.DataAccess.Models
{

    public partial class UserGadget
    {
        public int UserGadgetId { get; set; }
        public int UserId { get; set; }
        public int GadgetId { get; set; }
        public string GadgetSettings { get; set; }
        public int DisplayColumn { get; set; }
        public int DisplayOrdinal { get; set; }
    
        public virtual Gadget Gadget { get; set; }
        public virtual User User { get; set; }
    }
}
